contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #parseseq channel"
    url: https://nfcore.slack.com/channels/parseseq
    about: Discussion about the nf-core/parseseq pipeline
